### ISSUE TITLE
'RongRTCLib/RongRTCEngine.h' file not found

### ISSUE THREAD

**Issue by zhuhon0821** [rongcloud/sealrtc-ios#2]
<img width="1377" alt="2018-12-22 10 26 53" src="https://user-images.githubusercontent.com/16450421/50369680-69569b80-05d4-11e9-85fb-5478ea214736.png">
<img width="1032" alt="2018-12-22 10 24 17" src="https://user-images.githubusercontent.com/16450421/50369683-6e1b4f80-05d4-11e9-9094-724cb45ba623.png">
<img width="918" alt="2018-12-22 10 28 18" src="https://user-images.githubusercontent.com/16450421/50369684-71164000-05d4-11e9-8a7d-ff4c0abe0cac.png">

**Comment by bjlinhong** [comment]
你好, 版本已经更新到3.0, 请下载本demo后, 到融云官网下载RongRTCLib.framework, 再添加到demo工程中
